"""del admin

Revision ID: 0664a059af2a
Revises: 3501d0c6c77d
Create Date: 2023-11-24 19:06:32.593626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0664a059af2a'
down_revision: Union[str, None] = '3501d0c6c77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
