"""add pet adopted

Revision ID: 2167eda840d9
Revises: 23f8802d91df
Create Date: 2023-11-25 12:45:08.967773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2167eda840d9'
down_revision: Union[str, None] = '23f8802d91df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('is_adopted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'is_adopted')
    # ### end Alembic commands ###
